config/routes.rb
Wms::Application.routes.draw do
  resources :addresses

  resources :products

  resources :providers

  resources :pre_receipts

  devise_for :users
  
  root to: 'home#index'
  
  get 'permission_denied' => "home#permission_denied"
  
  get 'resources/language/:language' => "resources#language"
  
  get 'users/new' => "users#new", as: "new_user"
  get 'users/report' => "users#report", as: "report_users"
  get 'users/:id' => "users#edit", as: "edit_user"
  delete 'users/:id/delete' => "users#destroy", as: "delete_user"
  post 'users/save' => "users#save"
  patch 'users/save' => "users#save"
  get 'users/:id/roles' => "users#roles"
  get 'users' => "users#index"
  
  resources :receipts, :except => :new do
    get "new" => :new, as: "new", on: :member
  end

  resources :dispatches

  resources :product_types

  get 'storages' => "storages#index", as: "storages"
  get 'storages/locate' => "storages#locate", as: "locate_storages"
  get 'storages/report' => "storages#report", as: "report_storages"

  post 'product_reports/report' => "product_reports#report", as: "report_product_reports"
  get 'product_reports' => "product_reports#index"

  get 'receipt_reports' => "receipt_reports#index"
  post 'receipt_reports/report' => "receipt_reports#report", as: "report_receipt_reports"
  
  resources :file_storages
  

  

end

app/models/provider.rb
# -*- encoding : utf-8 -*-
class Provider < ActiveRecord::Base
  resourcify
  
  validates :nome, :presence => true
  validates :email, :email => true
end

app/controllers/providers_controller.rb
# -*- encoding : utf-8 -*-
class ProvidersController < ApplicationController
  load_and_authorize_resource
  before_action :set_provider, only: [:show, :edit, :update, :destroy]

  def index
    @providers = Provider.all
  end

  def show
  end

  def new
    @provider = Provider.new
  end

  def edit
  end

  def create
    @provider = Provider.new(provider_params)
    if @provider.save
      redirect_to @provider, notice: 'Fornecedor salvo com sucesso.'
    else
      render action: 'new'
    end
  end

  def update
    if @provider.update(provider_params)
      redirect_to @provider, notice: 'Fornecedor salvo com sucesso.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @provider.destroy
    redirect_to providers_url
  end

  private
    def set_provider
      @provider = Provider.find(params[:id])
    end

    def provider_params
      params.require(:provider).permit(:nome, :endereco, :cidade, :pais, :email, :contato, :telefone)
    end
end

app/helpers/providers_helper.rb
# -*- encoding : utf-8 -*-
module ProvidersHelper
end

app/views/providers/_form.html.erb
<div class="row-fluid">

	<div class="span12">


		<div class="widget wgreen">

			<div class="widget-head">
				<div class="pull-left">Cadastro de Novo Fornecedor</div>
				<div class="clearfix"></div>
			</div>

			<div class="widget-content">
				<div class="padd">

					<%= form_for(@provider) do |f| %>
					<% if @provider.errors.any? %>
					<div id="error_explanation">
						<h2><%= pluralize(@provider.errors.count, "error") %> prohibited this provider from being saved:</h2>

						<ul>
							<% @provider.errors.full_messages.each do |msg| %>
							<li><%= msg %></li>
							<% end %>
						</ul>
					</div>
					<% end %>

					<div class="row-fluid">
						<div class="span6">
							<%= f.label :nome %>
							<%= f.text_field :nome %>
						</div>
						<div class="span6">
							<%= f.label :contato %>
							<%= f.text_field :contato %>
						</div>
					</div>

					<div class="row-fluid">
						<div class="span5">
							<%= f.label :endereco, "Endereço" %>
							<%= f.text_field :endereco %>
						</div>
						<div class="span4">
							<%= f.label :cidade %>
							<%= f.text_field :cidade %>
						</div>
						<div class="span3">
							<%= f.label :pais %>
							<%= f.text_field :pais %>
						</div>
					</div>
					
					<div class="row-fluid">
						<div class="span6">
							<%= f.label :email, 'E-mail' %>
							<%= f.text_field :email %>
						</div>
						
						<div class="span6">
							<%= f.label :telefone %>
							<%= f.text_field :telefone %>
						</div>
					</div>

					<div class="actions">
						<%= f.submit "Cadastrar", :class => "btn btn-inverse" %>
					</div>
					<% end %>

				</div>
			</div>
		</div>

	</div>

</div>

app/views/providers/edit.html.erb
<div class="page-head">
	<h2 class="pull-left">Fornecedores
	</h2>
	<div class="bread-crumb pull-right">
		<a href="/"><i class="icon-home"></i> Home</a> 
		<!-- Divider -->
		<span class="divider">/</span> 
		<a href="#" class="bread-current">Fornecedores</a>
	</div>
	<div class="clearfix"></div>
</div>

<%= render 'form' %>

<%= link_to 'Voltar', providers_path,  :class => "btn btn-link" %>

app/views/providers/index.html.erb
<div class="page-head">
	<h2 class="pull-left">Fornecedores
	</h2>
	<div class="bread-crumb pull-right">
		<a href="/"><i class="icon-home"></i> Home</a> 
		<!-- Divider -->
		<span class="divider">/</span> 
		<a href="#" class="bread-current">Fornecedores</a>
	</div>
	<div class="clearfix"></div>
</div>

<div class="widget wgreen">

	<div class="widget-head">
		<div class="widget-icons pull-left">
			<%= link_to raw('<i class="icon-plus"></i> Novo fornecedor'), new_provider_path %>
		</div>
		<div class="clearfix"></div>
	</div>

	<div class="widget-content">

		<table class="table table-bordered table-striped" id="reportProviders">
			<thead>
				<tr>
					<th>Nome</th>
					<th>Endereco</th>
					<th>Cidade</th>
					<th>País</th>
					<th>Opções</th>
					<th></th>
				</tr>
			</thead>

			<tbody>
				<% @providers.each do |provider| %>
				<tr>
					<td><%= provider.nome %></td>
					<td><%= provider.endereco %></td>
					<td><%= provider.cidade %></td>
					<td><%= provider.pais %></td>
					<td><%= link_to 'Editar', edit_provider_path(provider) %></td>
					<td><%= link_to 'Excluir', provider, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
				</tr>
				<% end %>
			</tbody>
		</table>

	</div>
</div>

app/views/providers/new.html.erb
<div class="page-head">
	<h2 class="pull-left">Fornecedores
	</h2>
	<div class="bread-crumb pull-right">
		<a href="/"><i class="icon-home"></i> Home</a> 
		<!-- Divider -->
		<span class="divider">/</span> 
		<a href="#" class="bread-current">Fornecedores</a>
	</div>
	<div class="clearfix"></div>
</div>

<%= render 'form' %>

<%= link_to 'Voltar', providers_path, :class => "btn btn-link" %>

app/views/providers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @provider.nome %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @provider.endereco %>
</p>

<p>
  <strong>Cidade:</strong>
  <%= @provider.cidade %>
</p>

<p>
  <strong>Pais:</strong>
  <%= @provider.pais %>
</p>

<p>
  <strong>Contato:</strong>
  <%= @provider.contato %>
</p>

<p>
  <strong>E-mail:</strong>
  <%= @provider.email %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @provider.telefone %>
</p>

<%= link_to 'Editar', edit_provider_path(@provider) %> |
<%= link_to 'Voltar', providers_path %>