config/routes.rb
Wms::Application.routes.draw do
  resources :addresses

  resources :products

  resources :providers

  resources :pre_receipts

  devise_for :users
  
  root to: 'home#index'
  
  get 'permission_denied' => "home#permission_denied"
  
  get 'resources/language/:language' => "resources#language"
  
  get 'users/new' => "users#new", as: "new_user"
  get 'users/report' => "users#report", as: "report_users"
  get 'users/:id' => "users#edit", as: "edit_user"
  delete 'users/:id/delete' => "users#destroy", as: "delete_user"
  post 'users/save' => "users#save"
  patch 'users/save' => "users#save"
  get 'users/:id/roles' => "users#roles"
  get 'users' => "users#index"
  
  resources :receipts, :except => :new do
    get "new" => :new, as: "new", on: :member
  end

  resources :dispatches

  resources :product_types

  get 'storages' => "storages#index", as: "storages"
  get 'storages/locate' => "storages#locate", as: "locate_storages"
  get 'storages/report' => "storages#report", as: "report_storages"

  post 'product_reports/report' => "product_reports#report", as: "report_product_reports"
  get 'product_reports' => "product_reports#index"

  get 'receipt_reports' => "receipt_reports#index"
  post 'receipt_reports/report' => "receipt_reports#report", as: "report_receipt_reports"
  
  resources :file_storages
  

  

end

app/models/user.rb
# -*- encoding : utf-8 -*-
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/users_controller.rb
# -*- encoding : utf-8 -*-
class UsersController < ApplicationController
  load_and_authorize_resource
  respond_to :json, :html, :pdf
  
  def index
    @users = User.all
    respond_with(:users => @users)
  end
  
  def new
    @user = User.new
    @roles = Role.all
  end
  
  def edit
    @user = User.find(params[:id])
    @roles = Role.all
    respond_with(@user)
  end
  
  def save
    set_user
    if (params[:user][:id] == "")      
      if @user.save
        redirect_to action: 'index'
      else
        render action: 'new'
      end
    else
      if @user.update(user_params)
        redirect_to action: 'index'
      else
        render action: 'new'
      end
    end
  end
  
  def roles
    @roles = User.find(params[:id]).roles.select("id, name")
    respond_with(@roles)
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_path }
    end
  end
  
  def show
  end
  
  def report
    @users = User.all
    respond_with(@users, :responder => CallResponder)
  end
  
  private
    def split_roles_and_process
      if !params[:roles].empty?
        params[:roles].split(",").reject!(&:blank?).each {|r|
          role = Role.find(r)
          @user.add_role(role.name.to_sym)
        }
      end
    end
  
    def set_user
      if params[:user][:id] == ""
        @user = User.new(user_params)
        split_roles_and_process
      else
        @user = User.find_by_email(params[:user][:email])
        split_roles_and_process
      end
    end

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :id)
    end
end

app/helpers/users_helper.rb
# -*- encoding : utf-8 -*-
module UsersHelper
  
  def roles_to_view(roles)
    roles.map {|r| r.name }.join(", ")
  end
end

app/views/users/_form.html.erb
<div class="row-fluid">

	<div class="span12">

		<div class="widget wgreen" ng-controller="UserCtrl" data-ng-init="init(<%= @user.id%>)">

			<div class="widget-head">
				<div class="pull-left">Cadastro de Novo Usuário</div>
				<div class="clearfix"></div>
			</div>

			<div class="widget-content">
				<div class="padd">

					<%= form_for(@user, url: {action: "save"}) do |f| %>
						<% if @user.errors.any? %>
						<div id="error_explanation">
							<h2><%= pluralize(@user.errors.count, "error") %> prohibited this product from being saved:</h2>

							<ul>
								<% @user.errors.full_messages.each do |msg| %>
								<li><%= msg %></li>
								<% end %>
							</ul>
						</div>
						<% end %>
						
						<%= f.text_field :id %>

						<div class="row-fluid">
							<div class="span7">
								<%= f.label :email, 'E-mail' %>
								<%= f.text_field :email %>
							</div>
						</div>
						<div class="row-fluid">
							<div class="span4">
								<%= f.label :password, "Senha" %>
								<%= f.text_field :password %>
							</div>
							<div class="span4">
								<%= f.label :password_confirmation, "Repita a senha" %>
								<%= f.text_field :password_confirmation %>
							</div>
							<div class="span4">
								<label>Roles: </label>
								<%= select_tag "roles_to_add", options_from_collection_for_select(@roles, :id, :name), :'ng-model' => 'selectedProfile', :include_blank => true %>
								<button class="btn btn-primary" type="button" ng-click="addProfile()">Adicionar</button>
								<%= text_field_tag :roles, nil, :'ng-model' => 'selectedRoles' %>
								<table class="table table-bordered table-striped">
									<thead>
										<tr>
											<th>Perfil</th>
											<th>Opções</th>
										</tr>
									</thead>
									<tbody>
										<tr ng-repeat="profile in profiles">
											<td>{{profile.name}}</td>
											<td ng-click="removeProfile(profile.id)">Excluir</td>
										</tr>                                                              
									</tbody>
								</table>
							</div>
							
						</div>
						<div class="actions">
							<%= f.submit "Cadastrar", :class => "btn btn-inverse" %>
						</div>
						
					<% end %>
				</div>
			</div>
		</div>  

	</div>

</div>

app/views/users/edit.html.erb
<div class="page-head">
	<h2 class="pull-left">Usuários 
	</h2>
	<div class="bread-crumb pull-right">
		<a href="/"><i class="icon-home"></i> Home</a> 
		<!-- Divider -->
		<span class="divider">/</span> 
		<a href="#" class="bread-current">Usuários</a>
	</div>
	<div class="clearfix"></div>
</div>

<%= render 'form' %>

<%= link_to 'Voltar', users_path, :class => "btn btn-link" %>

app/views/users/index.html.erb
<div class="page-head">
	<h2 class="pull-left">Usuários 
	</h2>
	<div class="bread-crumb pull-right">
		<a href="/"><i class="icon-home"></i> Home</a> 
		<!-- Divider -->
		<span class="divider">/</span> 
		<a href="#" class="bread-current">Usuários</a>
	</div>
	<div class="clearfix"></div>
</div>



<div class="widget wgreen">

	<div class="widget-head">
		<div class="widget-icons pull-left">
			<%= link_to raw('<i class="icon-plus"></i> Novo usuário'), new_user_path %>
		</div>
		<div class="clearfix"></div>
	</div>

	<div class="widget-content">

		<table class="table table-bordered table-striped" id="reportUsers">
			<thead>
				<tr>
					<th>E-mail</th>
					<th>Perfis</th>
					<th>Opções</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<% @users.each do |user| %>
					<tr>
						<td><%= user.email %></td>
						<td><%= roles_to_view(user.roles) %></td>
						<td><%= link_to 'Editar', edit_user_path(user) %></td>
						<td><%= link_to 'Excluir', delete_user_path(user), method: :delete, data: { confirm: 'Tem certeza?' } %></td>
					</tr>
				<% end %>                                                                    
			</tbody>
		</table>

	</div>

</div>

app/views/users/new.html.erb
<div class="page-head">
	<h2 class="pull-left">Produtos </h2>
	<div class="bread-crumb pull-right">
		<a href="/"><i class="icon-home"></i> Home</a> 
		<!-- Divider -->
		<span class="divider">/</span> 
		<a href="#" class="bread-current">Usuários</a>
	</div>
	<div class="clearfix"></div>
</div>

<%= render 'form' %>

<%= link_to 'Voltar', users_path, :class => "btn btn-link" %>