config/routes.rb
Wms::Application.routes.draw do
  resources :addresses

  resources :products

  resources :providers

  resources :pre_receipts

  devise_for :users
  
  root to: 'home#index'
  
  get 'permission_denied' => "home#permission_denied"
  
  get 'resources/language/:language' => "resources#language"
  
  get 'users/new' => "users#new", as: "new_user"
  get 'users/report' => "users#report", as: "report_users"
  get 'users/:id' => "users#edit", as: "edit_user"
  delete 'users/:id/delete' => "users#destroy", as: "delete_user"
  post 'users/save' => "users#save"
  patch 'users/save' => "users#save"
  get 'users/:id/roles' => "users#roles"
  get 'users' => "users#index"
  
  resources :receipts, :except => :new do
    get "new" => :new, as: "new", on: :member
  end

  resources :dispatches

  resources :product_types

  get 'storages' => "storages#index", as: "storages"
  get 'storages/locate' => "storages#locate", as: "locate_storages"
  get 'storages/report' => "storages#report", as: "report_storages"

  post 'product_reports/report' => "product_reports#report", as: "report_product_reports"
  get 'product_reports' => "product_reports#index"

  get 'receipt_reports' => "receipt_reports#index"
  post 'receipt_reports/report' => "receipt_reports#report", as: "report_receipt_reports"
  
  resources :file_storages
  

  

end

app/models/storage.rb
class Storage
  include ActiveModel::Model
	attr_accessor :product, :receipt, :dispatch, :storage, :history_receipts, :history_dispatches

	def locate(filtros)	
    	date = date_format(filtros[:data])
		pre_receipts = filtra_pre_receipts(filtros, date)
		dispatches = filtra_dispatches(filtros, date)
		calcula_armazenamento(pre_receipts, dispatches, date)	
	end

	def diferenca
		self.storage = receipt - dispatch
	end

	private		

		def filtra_dispatches(filtros, date)
			dispatches = Dispatch.includes([:product, :address]).references([:product, :address]).where('expedicao <= ?', date)			
			if filter_valid?(filtros[:product_type_id])
				dispatches = dispatches.where("products.product_type_id = ?", filtros[:product_type_id])
			end
			if filter_valid?(filtros[:product_id])
				dispatches = dispatches.where("products.id = ?", filtros[:product_id])
			end
			if filter_valid?(filtros[:address_id])
				dispatches = dispatches.where("addresses.id = ?", filtros[:address_id])
			end
			dispatches
		end

		def filtra_pre_receipts(filtros, date)
			pre_receipts = PreReceipt.includes([:product, :receipt, :address]).references([:product, :receipt, :address]).where('receipts.data_recebimento <= ? and receipts.id is not null', date)			
			if filter_valid?(filtros[:product_type_id])
				pre_receipts = pre_receipts.where("products.product_type_id = ?", filtros[:product_type_id])
			end
			if filter_valid?(filtros[:product_id])
				pre_receipts = pre_receipts.where("products.id = ?", filtros[:product_id])
			end
			if filter_valid?(filtros[:address_id])
				pre_receipts = pre_receipts.where("addresses.id = ?", filtros[:address_id])
			end
			pre_receipts
		end
    
    def filter_valid?(filter)
      !filter.nil? && filter.to_i > 0
    end

    def date_format(date)
      date.split("/").reverse.join("-")
    end
  
		def initialize_storage(product, receipt, dispatch)
			storage = Storage.new
			storage.product = product
			storage.receipt = receipt
			storage.dispatch = dispatch
			storage.history_receipts = Array.new
			storage.history_dispatches = Array.new			
			storage
		end

		def create_receipt_history(item)
			receipt_history = HistoryReceipt.new
			receipt_history.pre_receipt = item
			receipt_history.receipt = item.receipt			
			receipt_history
		end
    	    	
    def preenche_dispatch_or_pre_receipt(itens, storages, type)
			itens.each {|item|
				product_index = procura_produto(item.product_id, storages)
				unless product_index.nil? 
					storage = storages[product_index]					
					storage.receipt = storage.receipt.+(item.quantidade.to_i - item.receipt.qtde_avariada.to_i) if type == Receipt
			        storage.dispatch = storage.dispatch.+(item.quantidade.to_i) if type == Dispatch				        
			        if type == Receipt
			        	receipt_history = create_receipt_history(item)
			        	storage.history_receipts << receipt_history
			        end				        					        				        
			        storage.history_dispatches << item if type == Dispatch
					storage.diferenca
					storages[product_index] = storage					
				else
					storage = initialize_storage(item.product, item.quantidade.to_i - item.receipt.qtde_avariada.to_i, 0) if type == Receipt
         			storage = initialize_storage(item.product, 0, item.quantidade.to_i) if type == Dispatch
         			if type == Receipt
			        	receipt_history = create_receipt_history(item)
			        	storage.history_receipts << receipt_history
			        end	
         			storage.history_dispatches << item if type == Dispatch
					storage.diferenca
					storages << storage
				end
			}
			storages
    end

		def calcula_armazenamento(pre_receipts, dispatches, data)
			storages = Array.new
			storages = preenche_dispatch_or_pre_receipt(pre_receipts, storages, Receipt)			
			storages = preenche_dispatch_or_pre_receipt(dispatches, storages, Dispatch)
			storages
		end		
		
		def procura_produto(id, storages)			
			product_index = nil
			storages.each_with_index { |storage, index|
				if id == storage.product.id 
					product_index = index
					break
				end
      		}
			product_index
		end
end

app/controllers/storages_controller.rb
class StoragesController < ApplicationController
	skip_before_filter :verify_authenticity_token, :only => [:report]	
	respond_to :json, :html, :pdf
	load_and_authorize_resource	
	
	def index
		@addresses = Address.all.to_set.classify {
			|address| address.address
		}
		@product_types = ProductType.all	
		@products = Product.all	
	end

	def locate				
		storage = Storage.new		
		@storages = storage.locate(params)
		respond_to do |format|
			format.json { render :json => @storages.to_json}			
		end		
	end

	def report
		storage = Storage.new		
		@storages = storage.locate(params)
		respond_with(@storages, :responder => CallResponder)
	end

end

app/helpers/storages_helper.rb
module StoragesHelper
end

app/views/storages/index.html.erb
<div class="page-head">
	<h2 class="pull-left">Armazenamento
	</h2>
	<div class="bread-crumb pull-right">
		<a href="/"><i class="icon-home"></i> Home</a> 
		<!-- Divider -->
		<span class="divider">/</span> 
		<!-- <%= link_to 'Expedição', dispatches_path, {:class => "bread-current"} %> -->
		<a href="#" class="bread-current">Armazenamento</a>
	</div>
	<div class="clearfix"></div>
</div>



<div class="widget wgreen">

	<div class="widget-head">
		<div class="widget-icons pull-left">
			Filtro
		</div>		
		<div class="clearfix"></div>
	</div>

	<div class="widget-content" ng-controller="StoragesController" data-ng-init="init()">
		<!-- TODO: colocar essa concat num helper e testar -->
		<form action="<%=report_storages_path(:format => :pdf)%>" method="GET">
				<div class="row-fluid">
					<div class="span3">
						<label>Data</label>
						<input id="data" type="date" name="data" ng-model="data" ng-change="recarregar()">
					</div>					
				</div>
				<div class="row-fluid">
					<div class="span6">
						<label for="address_id">Endereço</label>
						<select class="select-2" id="address_id" name="address_id" ng-model="address" ng-change="recarregar()">
							<option></option>
							<option value="">Todos</option>
							<% @addresses.each do |parent, address|%>
								<% if !parent.nil? %>
									<optgroup label="<%=parent.nome%>">
										<% address.each do |address| %>
											<option value="<%=address.id%>"><%=address.nome%></option>
										<% end %>
									</optgroup>
								<% end %>								  	
							<%end%>
						</select>
					</div>
				</div>
				<br/>
				<div class="row-fluid">
					<div class="span6">
						<label for="product_type_id">Tipo de Produto</label>
						<select class="select-2" id="product_type_id" name="product_type_id" ng-model="product_type" ng-change="recarregar()">
							<option></option>				
							<option value="">Todos</option>			
							<% @product_types.each do |product_type|%>
								<option value="<%=product_type.id%>"><%=product_type.descricao%></option>					  	
							<%end%>
						</select>
					</div>
					<div class="span6">
						<label for="product_id">Produto</label>
						<select class="select-2" id="product_id" name="product_id" ng-model="product" ng-change="recarregar()">
							<option></option>				
							<option value="">Todos</option>			
							<% @products.each do |product|%>
								<option value="<%=product.id%>"><%=product.name%></option>					  	
							<%end%>
						</select>
					</div>					
				</div>
				<div class="actions">
					<button type="submit" class="btn btn-primary">Imprimir</button>								
				</div>
			</form>		
			<hr></hr>
			<h5>Resultados da pesquisa</h5>
			<table class="table table-bordered table-striped" id="storagesTable">
				<thead>
					<tr>
						<th>Produto</th>
						<th>Recebimento</th>
						<th>Expedicao</th>
						<th>Armazenado</th>
						<th></th>
					</tr>
				</thead>
				<tbody>			
					<tr ng-repeat-start="storage in storages">						
						<td>{{storage.product.name}}</td>
						<td>{{storage.receipt}}</td>
						<td>{{storage.dispatch}}</td>
						<td>{{storage.storage}}</td>
						<td> <button type="button" class="btn btn-primary detail">Detalhes</button> </td>
					</tr>
					<tr class="next hide" ng-repeat-end>
						<td colspan="5">
							<table class="table table-bordered table-striped">
								<thead>
									<th>Tipo</th>
									<th>Data</th>
									<th>Quantidade</th>							
									<th>Avarias</th>
								</thead>
								<tbody>
									<tr ng-repeat="history_receipt in storage.history_receipts">
										<td>Recebimento</td>
										<td>{{history_receipt.receipt.data_recebimento}}</td>
										<td>{{history_receipt.pre_receipt.quantidade}}</td>
										<td>{{history_receipt.receipt.qtde_avariada}}</td>
									</tr>
									<tr ng-repeat="history_dispatche in storage.history_dispatches">
										<td>Expedição</td>
										<td>{{history_dispatche.expedicao}}</td>
										<td>{{history_dispatche.quantidade}}</td>
										<td>-</td>
									</tr>
								</tbody>								
							</table>
						</td>
					</tr>
				</tbody>
			</table>
		</div>	
	</div>

</div>

app/views/storages/locate.html.erb
<div class="page-head">
	<div class="bread-crumb pull-right">
		<a href="/"><i class="icon-home"></i> Home</a> 
		<!-- Divider -->
		<span class="divider">/</span> 
		<a href="#" class="bread-current">Armazenamento</a>
	</div>
	<div class="clearfix"></div>
</div>

<div class="widget wgreen">

	<div class="widget-head">
		<div class="widget-icons pull-left">
			Armazenamento em 
			<%= params[:data].to_time.to_s(:date) %>
		</div>		
		<div class="clearfix"></div>
	</div>

	<table class="table table-bordered table-striped">
		<thead>
			<tr>
				<th>Produto</th>
				<th>Recebimento</th>
				<th>Expedicao</th>
				<th>Armazenado</th>
			</tr>
		</thead>
		<tbody>
			<% @storages.each do |storage| %>
				<tr>
					<td><%= storage.product.name %></td>
					<td><%= storage.receipt %></td>
					<td><%= storage.dispatch %></td>
					<td><%= storage.storage %></td>
				</tr>
			<% end %>
		</tbody>
	</table>

</div>

<%= link_to "Voltar", storages_path, :class => "btn btn-primary" %>