config/routes.rb
Wms::Application.routes.draw do
  resources :addresses

  resources :products

  resources :providers

  resources :pre_receipts

  devise_for :users
  
  root to: 'home#index'
  
  get 'permission_denied' => "home#permission_denied"
  
  get 'resources/language/:language' => "resources#language"
  
  get 'users/new' => "users#new", as: "new_user"
  get 'users/report' => "users#report", as: "report_users"
  get 'users/:id' => "users#edit", as: "edit_user"
  delete 'users/:id/delete' => "users#destroy", as: "delete_user"
  post 'users/save' => "users#save"
  patch 'users/save' => "users#save"
  get 'users/:id/roles' => "users#roles"
  get 'users' => "users#index"
  
  resources :receipts, :except => :new do
    get "new" => :new, as: "new", on: :member
  end

  resources :dispatches

  resources :product_types

  get 'storages' => "storages#index", as: "storages"
  get 'storages/locate' => "storages#locate", as: "locate_storages"
  get 'storages/report' => "storages#report", as: "report_storages"

  post 'product_reports/report' => "product_reports#report", as: "report_product_reports"
  get 'product_reports' => "product_reports#index"

  get 'receipt_reports' => "receipt_reports#index"
  post 'receipt_reports/report' => "receipt_reports#report", as: "report_receipt_reports"
  
  resources :file_storages
  

  

end

app/models/product.rb
# -*- encoding : utf-8 -*-
class Product < ActiveRecord::Base
  resourcify
  
  belongs_to :provider
  belongs_to :product_type
  
  validates :name, :codigo, :provider, :product_type_id, :presence => true
  
  def volume
    altura  * largura * comprimento
  end
  
  def area
    largura * comprimento
  end

  def locate(filtros)
    @products = Product.all  
    if (!filtros[:name].nil? && filtros[:name] != '')       
      @products = @products.where('name = ?', filtros[:name])
    end
    if (!filtros[:product_type_id].nil? && filtros[:product_type_id].to_i > 0)       
      @products = @products.where('product_type_id = ?', filtros[:product_type_id])
    end
    if (!filtros[:provider_id].nil? && filtros[:provider_id].to_i > 0)       
      @products = @products.where('provider_id = ?', filtros[:provider_id])
    end
    if (!filtros[:codigo].nil? && filtros[:codigo] != '')       
      @products = @products.where('codigo = ?', filtros[:codigo])
    end
    @products
  end

end

app/models/product_type.rb
class ProductType < ActiveRecord::Base

	validates :descricao, :presence => true

end

app/controllers/products_controller.rb
# -*- encoding : utf-8 -*-
class ProductsController < ApplicationController
  load_and_authorize_resource
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
    @providers = Provider.all
    @product_types = ProductType.all
  end

  def edit
    @providers = Provider.all
    @product_types = ProductType.all
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to @product, notice: 'Produto salvo com sucesso.'
    else
      @providers = Provider.all
      @product_types = ProductType.all
      render action: 'new'
    end
  end

  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Produto salvo com sucesso.'
    else
      @providers = Provider.all
      @product_types = ProductType.all
      render action: 'edit'
    end
  end

  def destroy
    @product.destroy
    redirect_to products_url
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:codigo, :name, :provider_id, :peso, :altura, :largura, :comprimento, :product_type_id)
    end
end

app/helpers/products_helper.rb
# -*- encoding : utf-8 -*-
module ProductsHelper
end

app/views/products/_form.html.erb
<script>
	var $scope;
	function Product($scope) {
		$scope.productAltura = '<%= @product.altura %>';
		$scope.productComprimento = '<%= @product.comprimento %>';
		$scope.productLargura = '<%= @product.largura %>';
	};
</script>

<div class="row-fluid">

	<div class="span12">

		<div class="widget wgreen">

			<div class="widget-head">
				<div class="pull-left">Cadastro de Novo Produto</div>
				<div class="clearfix"></div>
			</div>

			<div class="widget-content">
				<div class="padd">

					<%= form_for(@product) do |f| %>
						<% if @product.errors.any? %>
						<div id="error_explanation">
							<h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

							<ul>
								<% @product.errors.full_messages.each do |msg| %>
								<li><%= msg %></li>
								<% end %>
							</ul>
						</div>
						<% end %>
						<div class="row-fluid">
							<div class="span12">
								<%= f.label :product_type_id, 'Tipo de Produto' %>
								<%= collection_select(:product, :product_type_id, @product_types, :id, :descricao ) %>
							</div>
						</div>
						<div class="row-fluid">
							<div class="span2">
								<%= f.label :codigo, 'Código' %>
								<%= f.text_field :codigo %>
							</div>
							<div class="span7">
								<%= f.label :name, 'Nome' %>
								<%= f.text_field :name %>
							</div>
							<div class="span3">
								<%= f.label :provider, 'Fornecedor' %>
								<%= collection_select(:product, :provider_id, @providers, :id, :nome ) %>
							</div>
						</div>
						<div class="row-fluid">
							<div class="span4">
								<%= f.label :peso %>
								<%= f.text_field :peso %>
							</div>
							<div class="span4" ng-controller="Product">
								<%= f.label :medidas %>
								<%= f.text_field :altura, :class => 'span3', :placeholder => 'A', "ng-model" => "productAltura" %>
								<%= f.text_field :largura, :class => 'span3', :placeholder => 'L', "ng-model" => "productLargura" %>
								<%= f.text_field :comprimento, :class => 'span3', :placeholder => 'C', "ng-model" => "productComprimento" %>
								<p>
									<strong>Área</strong>: 
									<span ng-show="productLargura && productComprimento">
										{{(productLargura * productComprimento)}}
									</span>
								</p>
								<p>
									<strong>Volume</strong>: 
									<span ng-show="productLargura && productComprimento && productAltura">
										{{(productLargura * productComprimento * productAltura)}}
									</span>
								</p>
							</div>
							<div class="actions">
								<%= f.submit "Cadastrar", :class => "btn btn-inverse" %>
							</div>
						</div>
					<% end %>


				</div>
			</div>
		</div>  

	</div>

</div>

app/views/products/edit.html.erb
<div class="page-head">
	<h2 class="pull-left">Produtos 
	</h2>
	<div class="bread-crumb pull-right">
		<a href="/"><i class="icon-home"></i> Home</a> 
		<!-- Divider -->
		<span class="divider">/</span> 
		<a href="#" class="bread-current">Produtos</a>
	</div>
	<div class="clearfix"></div>
</div>

<%= render 'form' %>

<%= link_to 'Voltar', products_path, :class => "btn btn-link" %>

app/views/products/index.html.erb
<div class="page-head">
	<h2 class="pull-left">Produtos 
	</h2>
	<div class="bread-crumb pull-right">
		<a href="/"><i class="icon-home"></i> Home</a> 
		<!-- Divider -->
		<span class="divider">/</span> 
		<a href="#" class="bread-current">Produtos</a>
	</div>
	<div class="clearfix"></div>
</div>



<div class="widget wgreen">

	<div class="widget-head">
		<div class="widget-icons pull-left">
			<%= link_to raw('<i class="icon-plus"></i> Novo produto'), new_product_path %>
		</div>
		<div class="clearfix"></div>
	</div>

	<div class="widget-content">

		<table class="table table-bordered table-striped" id="reportProducts">
			<thead>
				<tr>
					<th>Código</th>
					<th>Nome</th>
					<th>Fornecedor</th>
					<th>Peso</th>
					<th>Tipo</th>
					<th>Altura</th>
					<th>Largura</th>
					<th>Comprimento</th>
					<th>Opções</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<% @products.each do |product| %>
					<tr>
						<td><%= product.codigo %></td>
						<td><%= product.name %></td>
						<td><%= link_to product.provider.nome, product_path(product.provider) %></td>
						<td><%= product.peso %></td>
						<td><%= product.product_type.descricao unless product.product_type.nil? %></td>
						<td><%= product.altura %></td>
						<td><%= product.largura %></td>
						<td><%= product.comprimento %></td>
						<td><%= link_to 'Editar', edit_product_path(product) %></td>
						<td><%= link_to 'Excluir', product, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
					</tr>
				<% end %>                                                                    
			</tbody>
		</table>

	</div>

</div>

app/views/products/new.html.erb
<div class="page-head">
	<h2 class="pull-left">Produtos </h2>
	<div class="bread-crumb pull-right">
		<a href="/"><i class="icon-home"></i> Home</a> 
		<!-- Divider -->
		<span class="divider">/</span> 
		<a href="#" class="bread-current">Produtos</a>
	</div>
	<div class="clearfix"></div>
</div>

<%= render 'form' %>

<%= link_to 'Voltar', products_path, :class => "btn btn-link" %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @product.codigo %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Fornecedor:</strong>
  <%= @product.provider.nome %>
</p>

<p>
  <strong>Peso:</strong>
  <%= @product.peso %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @product.product_type.descricao %>
</p>

<p>
  <strong>Altura:</strong>
  <%= @product.altura %>
</p>

<p>
  <strong>Largura:</strong>
  <%= @product.largura %>
</p>

<p>
  <strong>Comprimento:</strong>
  <%= @product.comprimento %>
</p>

<%= link_to 'Editar', edit_product_path(@product) %> |
<%= link_to 'Voltar', products_path %>